# This is a basic workflow to help get started with actions

name : project4

# Control when the action will run. 
on:
  # triggers the workflow
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses : action/checkout@v2

      - name : Install Python 3
        uses : actions/setup-python@v1
        with:
          python-version : 3.7.15

      - name : Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name : Install tool
        run: |
          pip install .

      - name : Run unit tests
        run : python -m pytest -v
        